/*
 * This file is generated by jOOQ.
 */
package com.fimcraft.db.tables.records;


import com.fimcraft.db.tables.Verification;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerificationRecord extends UpdatableRecordImpl<VerificationRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1225169399;

    /**
     * Setter for <code>verification.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>verification.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>verification.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>verification.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Verification.VERIFICATION.UUID;
    }

    @Override
    public Field<String> field2() {
        return Verification.VERIFICATION.KEY;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public VerificationRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public VerificationRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public VerificationRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerificationRecord
     */
    public VerificationRecord() {
        super(Verification.VERIFICATION);
    }

    /**
     * Create a detached, initialised VerificationRecord
     */
    public VerificationRecord(String uuid, String key) {
        super(Verification.VERIFICATION);

        set(0, uuid);
        set(1, key);
    }
}
