/*
 * This file is generated by jOOQ.
 */
package com.fimcraft.db;


import com.fimcraft.db.tables.Users;
import com.fimcraft.db.tables.Verification;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>verification</code>.
     */
    public static final Verification VERIFICATION = Verification.VERIFICATION;
}
